server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: "mycards"
  datasource:
    url: jdbc:mysql://localhost:3306/my_bank_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: dong
    password: dong0807
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      archive:
        scan:
          packages: com.mybank.common.entity
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
jwt:
  secret: your_secret_key_should_be_at_least_256_bits_long_for_hs256_algorithm
  expiration: 86400000  # 24 hours in milliseconds
  tokenPrefix: "Bearer "
  headerName: "Authorization"
