server:
  port: 8082

spring:
  application:
    name: "myloans"
  datasource:
    url: jdbc:mysql://localhost:3306/my_bank_test?serverTimezone=UTC
    username: dong
    password: dong0807
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#jwt:
#  secret: your_secret_key_should_be_at_least_256_bits_long_for_hs256_algorithm
#  expiration: 86400000  # 24 hours in milliseconds
#  tokenPrefix: "Bearer "
#  headerName: "Authorization"
