server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: "myaccounts"
  datasource:
    url: jdbc:mysql://localhost:3306/my_bank_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: dong
    password: dong0807
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#app:
#  jwt:
#    secret: abcdefghijklmnOPQRSTUVWZYZ
#    expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.mybank.common.security: DEBUG
    com.mybank.myaccounts: DEBUG
