server:
  port: 8085

spring:
  application:
    name: "bankdesk"
  datasource:
    url: jdbc:mysql://localhost:3306/my_bank_test?serverTimezone=UTC
    username: dong
    password: dong0807
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      archive:
        scan:
          packages: com.mybank.common.entity
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
